### PR TITLE
Several bug fixes

### LINKED ISSUE #35: Question: RadioGroup - Missing state / description props
I noticed that, unlike the `TextField` and `TextArea` components, the `RadioGroup` component doesn’t support `state` and `description` props for showing an error state and message.

When reviewing [the RadioGroup docs](https://a-ui.github.io/core_components_react/?path=/docs/react-atoms-radios-group--docs), imagine a scenario where selecting one option is required. In that case, we’d need to display an error message if the user doesn’t make a selection and submits the form.

Is there an alternative way or UX pattern to handle this that I might be overlooking? Or is `state` and `description` something that should be added to the `RadioGroup` component?

Similar question as https://github.com/a-ui/core_components_react/issues/13

Thank you.

### LINKED ISSUE #42: Alert: missing margin between title and content for inline alerts
Version: 7.1.1
CSS: 7.1.1

When the inline `Alert` component is used with a title and content, the margin between the title and content does not match the spacing defined in the Figma design.

https://a-ui.github.io/core_components_react/?path=/story/react-molecules-alert--alert&args=theme:warning;inline:!true

Image

In Figma we can see some margin (12px) between title and content:

Image

### LINKED ISSUE #44: Upload component: Missing prop 'required'

### LINKED ISSUE #45: Checkbox component: Missing prop 'required'

### LINKED ISSUE #46: Datepicker component: Parameter 'id' not added to renderDescription
Linked to this issue:

Datepicker also contains a textfield component with prop `description={undefined}`
This causes the textField to not render an aria-describedby attribute which links our description to the input.

### LINKED ISSUE #47: RadioGroup component: Missing prop 'required'
Even if it is only for a visual asterix that shows something has to be selected

### LINKED ISSUE #49: The required asterix element in a label is read out by screenreaders
Add an aria-hidden=true attribute to the element that renders the red asterix next to a label.

```<span className="u-text-danger">*</span>```
-->
```<span className="u-text-danger" aria-hidden="true">*</span>```

### LINKED ISSUE #50: Autocomplete component: Missing prop 'disabled'

### LINKED ISSUE #53: Autocomplete component: not able to submit form onEnter
The autocomplete component contains a `handleKeyDown` function that prevents the default behaviour of the underlying input component to select values (single/multiple).
Please allow the default behaviour if the flyout isn't open

### LINKED ISSUE #55: Select component: adding value '' selects the first option
We don't want a value to be selected, but still want to be able to add a value as empty string (''). Currently this causes the first option to be selected.
We need to provide a value to make sure the Select component does not switch from uncontrolled to controlled

### PR DESCRIPTION
**Pull request by LukasYapla**

### CODE REVIEW

File: packages/antwerp-ui/react-components/src/lib/atoms/select/Select.tsx [hunk 1]
```diff
@@ -46,11 +49,13 @@ export function Select({
           disabled={disabled}
           name={name}
           id={id}
-          value={value}
-          defaultValue={(!value && placeholder) || undefined}
+          {...(isControlled
+            ? { value: !value ? '' : value }
+            : { defaultValue: '' }
+          )}
```
Comment (TriangleJuice) [inline packages/antwerp-ui/react-components/src/lib/atoms/select/Select.tsx]: I find
value={isControlled ? value : undefined}
defaultValue={!isControlled ? '' : undefined}

much more readable

File: packages/antwerp-ui/react-components/src/lib/atoms/select/Select.tsx
Comment (TriangleJuice) [inline packages/antwerp-ui/react-components/src/lib/atoms/select/Select.tsx]: Shouldn't that `key={value}` be removed here?

File: packages/antwerp-ui/react-components/src/lib/molecules/datepicker/Datepicker.tsx [hunk 2]
```diff
@@ -165,22 +165,27 @@ export function Datepicker({
     }
   };
 
+  const inputId = inputProps?.id ?? 'aui-text-field';
```
Comment (TriangleJuice) [inline packages/antwerp-ui/react-components/src/lib/molecules/datepicker/Datepicker.tsx]: The component must generate an error if no id is given, so no fallback should be provided.

File: packages/antwerp-ui/react-components/src/utils/render.utils.tsx [hunk 3]
```diff
@@ -79,3 +79,11 @@ export function renderAddOn(addOn?: ButtonAddOnProps, size?: 'small' | 'medium'
   }
   return null;
 }
+
+export function renderRequiredAsterisk(): ReactNode {
+  return (
+    <span className="u-text-danger" aria-hidden="true">
+      *
+    </span>
```
Comment (TriangleJuice) [inline packages/antwerp-ui/react-components/src/utils/render.utils.tsx:87]: Please put this on one line, so no unexpected spaces are renderer by the browser.

File: CHANGELOG.md [hunk 4]
```diff
@@ -5,6 +5,26 @@ All notable changes to this project will be documented in this file.
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
+## 7.11.2 - 2026-02-27
+
+### Added
+
+- Added `description` and `state` properties to the `RadioGroup` component
+- Added `required` property to the `Checkbox` component
+- Added `@testing-library/jest-dom` to the dependencies
```
Comment (TriangleJuice) [inline CHANGELOG.md]: Please remove this from the changelog.

File: package.json [hunk 5]
```diff
@@ -37,6 +37,7 @@
     "@nrwl/react": "15.8.7",
     "@nrwl/vite": "15.8.7",
     "@nrwl/workspace": "15.8.7",
+    "@testing-library/dom": "^10.4.0",
```
Comment (TriangleJuice) [inline package.json:40]: Can't we align the testing code style with the other components and remove this altogether?

**Review by TriangleJuice — CHANGES_REQUESTED** [review]
Thanks for the PR! I've made a few comments/suggestions.

File: package.json (hunk 5 above)
Comment (LukasYapla) [reply package.json:40]: I added `@testing-library/dom` because the tests weren’t running properly without it. After running `yarn install` and `yarn test`, no tests were detected:

 ```
 ➜  core_components_react git:(bugfix/several-bug-fixes) ✗ yarn test
 yarn run v1.22.22
 $ yarn nx test
  ❯ src/lib/molecules/autocomplete/Autocomplete.spec.tsx  (0 test)
  ❯ src/lib/molecules/upload/Upload.spec.tsx  (0 test)
  ❯ src/lib/atoms/range-slider/RangeSlider.spec.tsx  (0 test)
  ...
 ```

After adding `@testing-library/dom`, the tests ran as expected. It seems that the dependency is required for the tests, or am I missing something?

**Review by TriangleJuice — APPROVED** [review]
Thanks for the changes! Please check with @NicolasYapla for the `@testing-library/dom` change, since this is his setup. If it's necessary to make the tests run you can certainly leave it in the code.
The only requested change I didn't find is removing the `key={value}` from the Select component. If I'm not mistaken this unnecessarily force remounts the component every time the value changes.

File: packages/antwerp-ui/react-components/src/utils/render.utils.tsx (hunk 3 above)
Comment (NicolasYapla) [reply packages/antwerp-ui/react-components/src/utils/render.utils.tsx:87]: @TriangleJuice This is the default Prettier indentation and doesn't cause the browser to render spaces (it's considered indentation)

**Review by NicolasYapla — APPROVED** [review]
